version: "3.9"

services:
  core:
    platform: linux/x86_64  # https://github.com/GrahamDumpleton/wrapt/issues/199#issuecomment-1054696160
    build:
      context: ../
      dockerfile: docker/Dockerfile
    entrypoint: ./docker/runner.sh
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - docdb
    env_file:
      - ../src/config/.env.local

  docdb:
    image: elasticsearch:8.12.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
